### ISSUE TITLE
Please take a look at the picture, there is an obvious bug

### ISSUE THREAD

**Issue by DarkgreenWorld** [Straywave/ImmersiveSnow#10]
![屏幕截图 2023-10-23 234255](https://github.com/Straywave/ImmersiveSnow/assets/139338389/a69a2a5a-ae5a-4b46-b607-281b21b85494)

**Comment by DarkgreenWorld** [comment]
By the way, Minecraft, this foolish world generator, has created this spectacle - the alternating appearance of hot and arid tropical grasslands, hot and humid jungles, and humid biome in temperate or frigid zones where snow is allowed to accumulate.

**Comment by DarkgreenWorld** [comment]
![屏幕截图 2023-10-24 124928](https://github.com/Straywave/ImmersiveSnow/assets/139338389/e877e6d5-324f-41f6-a684-7abf0c709bf4)

**Comment by Straywave** [comment]
Fixed in Git -- chunks are now also added to queue when they are random-ticking.
