### ISSUE TITLE
Snow melts occasionally in the winter when it stops snowing

### ISSUE THREAD

**Issue by FeeeeK** [Straywave/ImmersiveSnow#11]
Sometimes after it stops snowing it disappears from the ground, same thing happens after a restart.
![image](https://github.com/Straywave/ImmersiveSnow/assets/26704473/667e9829-c187-45b0-9189-29f6477993cc)

**Comment by Straywave** [comment]
Fixed in Git (hopefully), will be released as v1.4.0 soon. Chunks are now added to queue if they are random-ticking.

You can also use `/snow forget` command to manually force nearby chunks to be reloaded. Or you can reload the world. But nevertheless it shouldn't happen anymore.

**Comment by FeeeeK** [comment]
> Fixed in Git (hopefully), will be released as v1.4.0 soon. Chunks are now added to queue if they are random-ticking.
> 
> You can also use `/snow forget` command to manually force nearby chunks to be reloaded. Or you can reload the world. But nevertheless it shouldn't happen anymore.
@Straywave 

Now with this change if you remove snow manually it will randomly appear without snowfall, I also suspect more lags due to chunks being updated multiple times
