### ISSUE TITLE
Entity lag

### ISSUE THREAD

**Issue by lawrencedumarey** [Straywave/ImmersiveSnow#12]
So when i use this mod with serene seasons, i get massive entity lag and chests take at least 10 seconds to load. Doesnt matter if there is snow or not, if there are a lot of entities or not its always lagging... Not sure how to fix this. I do use some performance mods it could perhaps be incompatible with this mod but probably not. Also im playing on 1.20.1 and here's a list of all the mods i currently have installed: 
[
<img width="1496" alt="Screenshot 2023-11-25 at 14 47 28" src="https://github.com/Straywave/ImmersiveSnow/assets/108006584/5718fa90-d715-4b49-94b3-f68a5bfc76a3">
](url)

**Comment by Mystic-Ervo** [comment]
I have the same problem here, I'm in 1.18.2

**Comment by Straywave** [comment]
Fixed in Git (hopefully), will be released as v1.4.0 soon.
