### ISSUE TITLE
[1.19.2] Massive lag with Immersive Weathering

### ISSUE THREAD

**Issue by valchiara** [Straywave/ImmersiveSnow#15]
When generating new chunks with Immersive Snow and Immersive Weathering installed, massive tps lag occurs.

Minecraft 1.19.2
Immersive Snow 1.3.0
Immersive Weathering 1.19.2-1.2.10

![img-2024-02-25-14-30-21](https://github.com/Straywave/ImmersiveSnow/assets/108143059/f4e2066c-4d46-4b3d-8f5f-63f711902932)

**Comment by Straywave** [comment]
Fixed in Git (soon will be released as v1.4.0), which should hopefully improve this, or even fix entirely -- there are a lot more checks in place, and newly-loaded chunks are offloaded to the next tick. However Immersive Weathering is not yet available for 1.20.4+ so I'm unable to test it.
