### ISSUE TITLE
[1.20.1] to intensive on the MSPT

### ISSUE THREAD

**Issue by zoqin** [Straywave/ImmersiveSnow#16]
**After a long testing of an issue that lead me (wrongly) to think that Snow Real Magic was a issue I identify Immersive Snow as the culpitre with the help of the kind SRM dev (not loading SRM at all still triggered the high lag issue).** 

The lag happen when loading chunk but also way past loading chunk 
All the previous testing was done while loading and while being fighting zombie in the snow in loaded chunk

I past you the test I did for SRM

----------------------------------

Here is the new batch of testing

**Legends**:
1=Yes 0=No
Warn snow= Presence of multiple `[Server thread/WARN] [minecraft/LevelChunk]: Tried to load a DUMMY block entity @ BlockPos{x=@@@, y=@@@, z=@@@} but found not block entity block Block{minecraft:snow}[layers=1] at location` in log

===================

**Methodology:**
I use the fresh install I previously made for testing with the same culpitre modpack
I launch the game and delete previous world to load a new one
(once for the batch of testing) I run /spark  --only-ticks-over 50
I give myself nature compass via creative in game panel
I run / spark profiler start
I search for "snow" in nature compass GUI I select Snowy Slopes then I reopen the GUI to teleport to it
I explore snowy surface until I can found a village and a tree cluster (if it was subjectively qucik to find I load a subjective amount of additional chunk)
I place myself in the laggiest snowy place I can find and summon and zombie. I hit him and hit surrounding snowy block with left and right click
I stop spark profiler I summon a new zombie I run an observable for 20 while doing similar fight behavior
I alt+F4
I copy and past there related information
I relaunch the game with different mod enable or disable (see the provided information) I repeat the step until the batch of test is done then I kill more zombie for sadistic reason

===================

**1. Chunky 1 Immersive Snow 1 SRM 1**

**Spark:**
https://spark.lucko.me/S3eGMw9ydh
**Observable:**
https://o.tas.sh/#Eb7Q5
**Log:**
Warn snow 1
[FirstTest.txt](https://github.com/Snownee/SnowRealMagic/files/14396110/FirstTest.txt)

-----------------------------

**2. Chunky 1 Immersive Snow 0 SRM 1**

**Spark:**
https://spark.lucko.me/8XgNB5Ct8Y
**Observable:**
https://o.tas.sh/#dY6q4
**Log:**
Warn snow 1
[2ndTest.txt](https://github.com/Snownee/SnowRealMagic/files/14396157/2ndTest.txt)

-----------------------------

**3. Chunky 0 Immersive Snow 0 SRM 1**

**Spark:**
https://spark.lucko.me/ZTHwYqwJKo
**Observable:**
https://o.tas.sh/#rODZk
**Log:**
Warn snow 1
[3Test.txt](https://github.com/Snownee/SnowRealMagic/files/14396229/3Test.txt)

**_Exceptionally additional test:_**
**Spark:**
https://spark.lucko.me/Cx83hy0y23
**Observable:**
https://o.tas.sh/#KdP7X
_(didn't find village structure at first so I made the first test then parkour way more to find structure village to make test with more parity but in the end as way more chunk was load I didn't know if which one would be the more interesting so I provide both anyway)_

-----------------------------

**4. Chunky 1 Immersive Snow 1 SRM 0**

**Spark:**
https://spark.lucko.me/7GFgiXAX84
**Observable:**
https://o.tas.sh/#mpVpq
**Log:**
Warn snow 0
[4Test.txt](https://github.com/Snownee/SnowRealMagic/files/14396746/4Test.txt)

_**Additionally test with --only-ticks-over 150 (I don't know feel it could be useful to test as I was already on this config)**_
**Spark:**
https://spark.lucko.me/vsXDmN3hc3

_No snowy village structure where to be found but it was a mess anyway I didn't feel like loading this kind of structure would be usefull anyway to innocent SRM of anywrong_

-------------------------------

Thanks for your consideration

**Comment by Alasofia** [comment]
Same here. Thought it was SRM, it's this.

**Comment by watermelon0guy** [comment]
Same. Did you find replacement?

**Comment by watermelon0guy** [comment]
Same. Did you find replacement? @zoqin @Alasofia

**Comment by Alasofia** [comment]
No. I ended up removing the mod from the modpack. @watermelon0guy

**Comment by watermelon0guy** [comment]
Thx for fast answer. It was just so unbearably slow on a beefy server (5 cores, 10 GB). And every player movement just kill performance. Maybe I just increase snow melting somehow

**Comment by Straywave** [comment]
Fixed in Git (hopefully), will be released as v1.4.0 soon.

**Comment by darceno** [comment]
@Straywave is this fix also in 1.3.2 for 1.20.1 forge/fabric?

**Comment by darceno** [comment]
I just saw [061125f](https://github.com/Straywave/ImmersiveSnow/commit/061125f4e1ce15cacb291eea6cc5331cb407ccda), so I assume you backported it. Great! In the Modrinth changelogs, I noticed that only version 1.4.0 mentioned 'Recalculate chunks when season changes,' and I thought that was the major fix.

**Comment by Straywave** [comment]
The "recalculate snow when season changes" is a new rewritten hook into each season mod, that resets all chunks in memory when the season changes (so, the world immediately reloads and recalculates upon transition from winter to spring, or spring to summer, etc.). One downside is that I still have RandomTick hook, which means nearby chunks will recalculate every so often on their own, which can break immersion, but it's a backup in case of maybe future season mod incompatibility.

Either way, the performance fixes are a separate thing, and are indeed present in the backported 1.3.2 :)

**Comment by mpustovoi** [comment]
I don't know why, but my game is struggling generating new chunks with this mod:

<img width="886" height="152" alt="Image" src="https://github.com/user-attachments/assets/cdbe1bd7-ba53-4ba4-9f9d-b361dab215ee" />

https://spark.lucko.me/QM9zUmzMhq
