### ISSUE TITLE
Console/log spam

### ISSUE THREAD

**Issue by samve000** [Straywave/ImmersiveSnow#17]
The log keeps spamming chunk [coordinates] has been sitting for 100 ticks, forgetting
![image](https://github.com/user-attachments/assets/3ac6b06a-50fc-4c35-947e-8c20b493c4d1)

I use the Fabric Seasons mod and immersive weathering too btw.

**Comment by Straywave** [comment]
Fixed in Git, will be released as v1.4.0 soon.
