### ISSUE TITLE
Hoping for a 1.21.1 update

### ISSUE THREAD

**Issue by PremiumRush** [Straywave/ImmersiveSnow#18]
As the title states, I am really hoping for this mod to update to 1.21 or 1.21.1.
This mod really is the only thing that makes Serene Seasons Playable to me.

I don't want to be annoying with asking _"Port This? Port That?"_ etc, I just wanna know if you plan to do this or not.

Kindest Regards!

**Comment by Straywave** [comment]
Done in Git, for versions 1.20.4, 1.21.1, and 1.21.4. However I had to drop 1.20.1 and below due to big changes in the building logic (mostly NeoForge). Will be released as 1.4.0 soon, if you want to test right now, you can download from GitHub Actions.
