### ISSUE TITLE
Very laggy integrated server spikes when loading new chunks

### ISSUE THREAD

**Issue by SewingChain77161** [Straywave/ImmersiveSnow#19]
I tested out this mod and, it gets your singleplayer world very laggy as if it was like a multiplayer server with bad connection, is there any fix to it? I am using this with some performance mods (embeddium + oculus for ex) im also using serene seasons + biomes o' plenty

**Comment by SewingChain77161** [comment]
Here is a spark test btw https://spark.lucko.me/iXgwuGGucF

**Comment by kocane** [comment]
Did you fix this? Is the solution perhaps to pregen chunks?

**Comment by Straywave** [comment]
Fixed in Git (hopefully), will be released as v1.4.0 soon.
