### ISSUE TITLE
Compatibility with "Serene Seasons Fix"?

### ISSUE THREAD

**Issue by kocane** [Straywave/ImmersiveSnow#21]
Is there any of the functionality in the [Serene Seasons Fix](https://www.curseforge.com/minecraft/mc-mods/serene-seasons-fix) mod that could seemingly cause issues with Immersive Snow?

**Comment by Straywave** [comment]
I don't think so, Immersive Snow only uses Serene Seasons for biome temperature calculation and reading the current season. The Hourglass integration is done by simply reading the current season and setting the time rate in the Hourglass config, but if there's any conflict with the relative season time, you can disable Hourglass integration and still have snow recalculation.
