### ISSUE TITLE
Any plans for NeoForge support??

### ISSUE THREAD

**Issue by Mystic-Ervo** [Straywave/ImmersiveSnow#22]
Since NeoForge is literally Forge but better (it has the original development team) I think that betting on a port for NeoForge would be a good option.

Many large mods (such as Sodium or Iris) are migrating to NeoForge due to its accessibility and ease of development, as well as being much more optimized and less problematic than Forge.

I find Serene Seasons unplayable without this mod, and I'm not the only one who thinks so. Another modloader option would be great for a lot of people.

**Comment by Straywave** [comment]
Done in Git, if you want you can download from GitHub Artifacts to test it. Will be released as 1.4.0 soon.
