### ISSUE TITLE
When the chunks are recaculated, it seems that snow under trees refuses to melt year round. 

### ISSUE THREAD

**Issue by FlyGuy240** [Straywave/ImmersiveSnow#4]
I know this is probably a vanilla mechanic, but as a side effect of chunk recalculations, snow spawns under the trees, then when spring roles around that snow doesn't melt.  Perhaps a simple/temporary fix would be allowing snow layers to melt without direct sunlight?

**Comment by Straywave** [comment]
Fixed in master, will be released as v1.3.0 in the coming days
