### ISSUE TITLE
[BUG]  [1.19.2]   Immersive Snow cannot run properly

### ISSUE THREAD

**Issue by fenlincao** [Straywave/ImmersiveSnow#5]
mod versions: 1.2.0
I only added the Serene Seasons mod , but Immersive Snow did not work properly, I can not find the reason, the following is the log.Thanks!
https://gist.github.com/fenlincao/aac7af67487cf40ad338df083370870e

**Comment by Straywave** [comment]
Doesn't look like it's an issue with Immersive Snow. There's no stack trace at the end, looks like just a normal game log to me (albeit running in offline mode, hence the errors and warnings about retrieving profile key pairs)

**Comment by fenlincao** [comment]
Thanks, I will try again. I will close this issue for now and open it again if there is any problem.
